// Sample educational copy for the prototype.
const topics: Record<string, [string, string]> = {
 "Programlamaya Giriş": ["algoritma kurma, değişkenler, koşullar, döngüler ve fonksiyonlarla temel programlama becerileri kazandırmak", "develop basic programming skills through algorithms, variables, conditions, loops and functions"],
 "Veri Yapıları": ["verileri düzenlemek için uygun veri yapılarını seçme ve algoritmaların zaman ile bellek kullanımını değerlendirme becerisi kazandırmak", "develop the ability to select data structures and evaluate algorithm time and memory usage"],
 "İşletim Sistemleri": ["süreç, bellek, dosya ve kaynak yönetimini açıklayarak işletim sistemlerinin çalışma ilkelerini kavratmak", "explain operating system principles through process, memory, file and resource management"],
 "Bilgisayar Ağları": ["ağ katmanlarını, iletişim protokollerini ve veri iletim süreçlerini açıklayarak temel ağ problemlerini çözme becerisi kazandırmak", "develop an understanding of network layers, protocols and data transmission to solve basic networking problems"],
 "Yazılım Mühendisliğine Giriş": ["gereksinim analizinden bakıma kadar yazılım yaşam döngüsünü tanıtmak ve sistematik geliştirme alışkanlığı kazandırmak", "introduce the software lifecycle from requirements to maintenance and encourage systematic development"],
 "Nesne Yönelimli Programlama": ["sınıf, nesne, kalıtım ve çok biçimlilik kavramlarıyla modüler ve yeniden kullanılabilir yazılımlar geliştirmeyi öğretmek", "teach modular, reusable software development through classes, objects, inheritance and polymorphism"],
 "Yazılım Mimarisi": ["mimari yaklaşımları karşılaştırarak kalite gereksinimlerine uygun yazılım yapıları tasarlama becerisi kazandırmak", "develop the ability to compare architectural approaches and design software structures that meet quality requirements"],
 "Yazılım Testi": ["test senaryoları oluşturma, hataları belirleme ve yazılımın beklenen davranışını doğrulama becerisi kazandırmak", "develop skills in designing test cases, identifying defects and verifying expected software behaviour"],
 "Devre Analizi": ["temel devre yasalarını kullanarak elektrik devrelerindeki akım, gerilim ve güç ilişkilerini çözümlemeyi öğretmek", "teach analysis of current, voltage and power relationships using fundamental circuit laws"],
 "Elektronik": ["yarı iletken elemanların davranışlarını ve temel elektronik devrelerin çalışma ilkelerini kavratmak", "explain semiconductor behaviour and the operating principles of basic electronic circuits"],
 "Sinyaller ve Sistemler": ["sinyalleri zaman ve frekans alanlarında inceleme ve sistemlerin tepkilerini yorumlama becerisi kazandırmak", "develop skills in analysing signals in time and frequency domains and interpreting system responses"],
 "Kontrol Sistemleri": ["geri besleme, kararlılık ve sistem tepkisi kavramlarıyla temel kontrol çözümleri geliştirmeyi öğretmek", "teach basic control solutions through feedback, stability and system response"],
 "Temel Tasarım": ["biçim, oran, ritim, denge ve kompozisyon ilkeleriyle görsel düşünme ve tasarım ifade becerilerini geliştirmek", "develop visual thinking and design expression through form, proportion, rhythm, balance and composition"],
 "Mimari Tasarım": ["kullanıcı, yer ve işlev ilişkilerini değerlendirerek tutarlı mekânsal tasarım önerileri geliştirme becerisi kazandırmak", "develop coherent spatial proposals by evaluating relationships between users, site and function"],
 "Yapı Bilgisi": ["yapı bileşenleri, malzemeler ve yapım yöntemleri arasındaki ilişkileri teknik tasarım kararlarına aktarmayı öğretmek", "teach how relationships between building components, materials and construction methods inform technical design"],
 "Mimarlık Tarihi": ["yapıları tarihsel, kültürel ve toplumsal bağlamları içinde inceleyerek mimarlık anlayışlarının değişimini yorumlatmak", "interpret changes in architectural thought by examining buildings in their historical, cultural and social contexts"],
 "İç Mekân Tasarımı": ["kullanıcı ihtiyaçları, ergonomi ve işlev doğrultusunda iç mekân çözümleri geliştirme becerisi kazandırmak", "develop interior design solutions informed by user needs, ergonomics and function"],
 "Mobilya Tasarımı": ["işlev, malzeme, ergonomi ve üretim ilişkilerini gözeten mobilya tasarımları geliştirmeyi öğretmek", "teach furniture design that considers function, materials, ergonomics and manufacturing"],
 "Aydınlatma Tasarımı": ["doğal ve yapay ışığın mekân algısı ve görsel konfor üzerindeki etkilerini tasarım kararlarıyla ilişkilendirmek", "relate the effects of natural and artificial light on spatial perception and visual comfort to design decisions"],
 "Analiz": ["limit, süreklilik, türev ve integral kavramlarını matematiksel akıl yürütme ve problem çözmede kullanmayı öğretmek", "teach the use of limits, continuity, derivatives and integrals in mathematical reasoning and problem solving"],
 "Lineer Cebir": ["vektör uzayları, matrisler ve doğrusal dönüşümler üzerinden doğrusal problemleri modelleme becerisi kazandırmak", "develop modelling skills for linear problems through vector spaces, matrices and linear transformations"],
 "Diferansiyel Denklemler": ["değişim süreçlerini diferansiyel denklemlerle modelleme, çözme ve sonuçları yorumlama becerisi kazandırmak", "develop skills in modelling change through differential equations, solving them and interpreting results"],
 "Soyut Cebir": ["grup, halka ve cisim gibi cebirsel yapıları inceleyerek soyutlama ve ispat becerilerini geliştirmek", "develop abstraction and proof skills through algebraic structures such as groups, rings and fields"],
 "Mekanik": ["hareket, kuvvet, enerji ve momentum ilişkilerini kullanarak fiziksel sistemleri analiz etmeyi öğretmek", "teach analysis of physical systems through motion, force, energy and momentum"],
 "Elektrik ve Manyetizma": ["elektrik ve manyetik alanları temel yasalarla açıklamak ve fiziksel olaylara uygulama becerisi kazandırmak", "explain electric and magnetic fields through fundamental laws and apply them to physical phenomena"],
 "Optik": ["ışığın yayılması, girişim, kırınım ve görüntü oluşumu süreçlerini açıklama becerisi kazandırmak", "develop understanding of light propagation, interference, diffraction and image formation"],
 "Kuantum Fiziği": ["mikroskobik sistemleri kuantum kavramlarıyla açıklamak ve temel modellerin fiziksel anlamını yorumlatmak", "explain microscopic systems using quantum concepts and interpret the physical meaning of basic models"],
 "Statik": ["kuvvet ve moment dengesi ilkeleriyle durağan mühendislik sistemlerini çözümleme becerisi kazandırmak", "develop analysis of stationary engineering systems using force and moment equilibrium"],
 "Dinamik": ["cisimlerin hareketini kuvvet, enerji ve momentum yaklaşımlarıyla inceleme becerisi kazandırmak", "develop the ability to study motion through force, energy and momentum approaches"],
 "Termodinamik": ["enerji, ısı ve iş ilişkilerini termodinamik yasalarıyla inceleyerek sistem verimliliğini değerlendirmeyi öğretmek", "teach evaluation of system efficiency through thermodynamic laws and relationships between energy, heat and work"],
 "Makine Elemanları": ["makine bileşenlerini yük, dayanım ve çalışma koşullarına göre seçme ve boyutlandırma becerisi kazandırmak", "develop the ability to select and size machine components according to loads, strength and operating conditions"],
 "Olasılık": ["rastlantısal olayları, olasılık dağılımlarını ve belirsizliği matematiksel olarak modelleme becerisi kazandırmak", "develop mathematical modelling of random events, probability distributions and uncertainty"],
 "İstatistiksel Çıkarım": ["örneklem verilerinden tahmin ve hipotez testleri yoluyla sonuç çıkarma ve belirsizlikleri yorumlama becerisi kazandırmak", "develop inference from sample data through estimation and hypothesis testing while interpreting uncertainty"],
 "Regresyon Analizi": ["değişkenler arasındaki ilişkileri modelleme, model varsayımlarını değerlendirme ve tahminleri yorumlama becerisi kazandırmak", "develop skills in modelling relationships between variables, assessing assumptions and interpreting predictions"],
 "Zaman Serileri": ["zamana bağlı verilerde eğilim ve mevsimselliği inceleyerek uygun tahmin modelleri geliştirmeyi öğretmek", "teach forecasting model development through trends and seasonality in time-dependent data"],
 "İleri Algoritmalar": ["ileri algoritma tasarım yöntemlerini karşılaştırma ve çözümlerin doğruluk ile karmaşıklığını değerlendirme becerisi kazandırmak", "develop comparison of advanced algorithm design methods and evaluation of correctness and complexity"],
 "Makine Öğrenmesi": ["veriden öğrenen modelleri kurma, doğrulama ve genelleme başarısını eleştirel biçimde değerlendirme becerisi kazandırmak", "develop skills in building and validating learning models and critically evaluating generalisation"],
 "Araştırma Yöntemleri": ["araştırma sorusu oluşturma, kaynakları değerlendirme ve etik ilkelere uygun araştırma süreci planlama becerisi kazandırmak", "develop skills in framing research questions, reviewing literature and planning ethical research"],
 "Bilimsel Hesaplama": ["bilimsel problemleri sayısal yöntemlerle çözme ve hesaplama sonuçlarının hata ile kararlılığını değerlendirme becerisi kazandırmak", "develop numerical solutions to scientific problems and evaluate computational error and stability"],
 "Akademik İletişim": ["akademik metinleri anlama, kaynak gösterme ve düşünceleri yazılı ve sözlü olarak açık biçimde sunma becerisi kazandırmak", "develop skills in understanding academic texts, citing sources and communicating ideas clearly in writing and speech"],
 "Alan Projesi": ["programda edinilen bilgileri bir problem üzerinde birleştirme, proje sürecini planlama ve sonuçları gerekçeleriyle sunma becerisi kazandırmak", "integrate program knowledge in a project, plan the work and present results with supporting reasoning"],
 "Seçmeli Ders": ["öğrencinin ilgi alanlarına yönelik bilgi birikimini genişletmek ve farklı bakış açılarını kendi çalışma alanıyla ilişkilendirmesini desteklemek", "broaden knowledge in areas of interest and connect different perspectives with the student's field of study"]
};
export function getCourseAim(title: string) {
 const topic = topics[title];
 return topic ? {
  tr: "Bu ders, " + topic[0].replace(/mak$/, "mayı").replace(/mek$/, "meyi") + " hedefler. Kavramların örnekler üzerinden ele alınmasıyla öğrencilerin öğrendiklerini uygulamaya aktarması ve çözüm yaklaşımlarını gerekçelendirmesi amaçlanır.",
  en: "This course aims to " + topic[1] + ". Examples support students in applying the concepts and explaining the reasoning behind their solutions."
 } : { tr: `Bu örnek ders, ${title} alanındaki temel kavramları tanıtmayı ve öğrencilerin bu bilgileri basit uygulamalarda kullanmasını hedefler.`, en: `This sample course introduces core concepts in ${title} and aims to help students apply them in basic exercises.` };
}

