const programAims: Record<string, { tr: string; en: string }> = {
  BIL: { tr: "Programın amacı; bilgisayar sistemlerinin tasarımı, geliştirilmesi ve değerlendirilmesi için gerekli temel bilgi ve becerileri kazandırmaktır. Algoritmik düşünme, yazılım geliştirme ve donanım bilgilerini bir araya getirerek farklı alanlardaki problemlere çözüm üretebilen; ekip çalışmasına, mesleki etik ilkelere ve sürekli öğrenmeye önem veren mühendisler yetiştirmeyi hedefler.", en: "The program aims to develop the knowledge and skills needed to design, build and evaluate computer systems. It combines algorithmic thinking, software development and hardware knowledge to support problem solving across different fields, with an emphasis on teamwork, professional ethics and lifelong learning." },
  YAZ: { tr: "Programın amacı; kullanıcı ihtiyaçlarını anlayarak güvenilir, sürdürülebilir ve geliştirilebilir yazılım çözümleri tasarlayabilen bireyler yetiştirmektir. Yazılım yaşam döngüsünün analiz, tasarım, kodlama, test ve bakım aşamalarında sistematik çalışma alışkanlığı kazandırmayı; teknik becerileri iletişim, ekip çalışması ve etik sorumlulukla desteklemeyi hedefler.", en: "The program aims to develop the ability to understand user needs and design reliable, maintainable and adaptable software. It encourages a systematic approach to analysis, design, implementation, testing and maintenance, supported by communication, teamwork and ethical responsibility." },
  ELE: { tr: "Programın amacı; elektrik ve elektronik sistemlerini bilimsel temellerle analiz edebilen, tasarlayabilen ve geliştirebilen mühendisler yetiştirmektir. Enerji, devreler ve haberleşme gibi alanlardaki problemlere güvenlik, verimlilik ve çevresel etkileri gözeten çözümler üretmeyi; deneysel bulguları yorumlama ve teknolojik gelişmelere uyum sağlama becerilerini kazandırmayı hedefler.", en: "The program aims to develop engineers who can analyse, design and improve electrical and electronic systems using scientific principles. It promotes solutions that consider safety, efficiency and environmental impact, alongside skills in interpreting experimental results and adapting to technological change." },
  MIM: { tr: "Programın amacı; insan, çevre ve yapı arasındaki ilişkileri değerlendirerek nitelikli yaşam alanları tasarlayabilen mimarlar yetiştirmektir. Yaratıcı düşünceyi teknik bilgiyle birleştirmeyi; kültürel mirasa, erişilebilirliğe ve sürdürülebilirliğe duyarlı tasarım kararları geliştirmeyi hedefler. Tasarımların görsel, yazılı ve sözlü olarak ifade edilmesi de bu yaklaşımın bir parçasıdır.", en: "The program aims to develop architects who can design quality living spaces by considering relationships between people, buildings and the environment. It brings creative thinking together with technical knowledge and encourages sensitivity to cultural heritage, accessibility and sustainability, supported by visual, written and verbal communication." },
  ICM: { tr: "Programın amacı; kullanıcıların fiziksel, sosyal ve estetik ihtiyaçlarına yanıt veren iç mekânlar tasarlayabilen bireyler yetiştirmektir. Malzeme, renk, aydınlatma ve ergonomi bilgisini bütüncül bir tasarım yaklaşımıyla kullanmayı; mekânsal çözümleri uygulanabilirlik, erişilebilirlik ve çevresel sorumluluk açısından değerlendirmeyi hedefler.", en: "The program aims to develop designers who can create interiors that respond to physical, social and aesthetic needs. It integrates materials, colour, lighting and ergonomics within a coherent design approach, considering feasibility, accessibility and environmental responsibility." },
  MAT: { tr: "Programın amacı; matematiksel kavramları derinlemesine anlayabilen, mantıksal çıkarımlar yapabilen ve problemleri farklı yöntemlerle çözebilen bireyler yetiştirmektir. Soyut düşünme ve ispat becerilerini geliştirmenin yanında, matematiksel bilgiyi modelleme ve disiplinler arası problemlerde kullanmayı; düşünceleri açık ve tutarlı biçimde ifade etmeyi hedefler.", en: "The program aims to develop a thorough understanding of mathematical concepts, logical reasoning and flexible problem-solving skills. Alongside abstraction and proof, it promotes the use of mathematics in modelling and interdisciplinary problems, with clear and consistent communication of ideas." },
  FIZ: { tr: "Programın amacı; doğa olaylarını bilimsel yöntemlerle inceleyebilen ve fiziksel süreçleri kuramsal ve deneysel yaklaşımlarla açıklayabilen bireyler yetiştirmektir. Ölçüm yapma, veri analizi, matematiksel modelleme ve eleştirel değerlendirme becerilerini geliştirmeyi; araştırma sürecinde doğruluk, sorgulama ve bilimsel etik ilkelerini benimsetmeyi hedefler.", en: "The program aims to develop the ability to investigate natural phenomena scientifically and explain physical processes through theory and experiment. It supports measurement, data analysis, mathematical modelling and critical evaluation, with an emphasis on accuracy, inquiry and research ethics." },
  "BIL-YL": { tr: "Programın amacı; bilgisayar mühendisliğinin belirli bir alanında uzmanlaşarak bağımsız araştırma yürütebilen bireyler yetiştirmektir. Bilimsel literatürü eleştirel biçimde değerlendirme, araştırma sorusu oluşturma, uygun yöntemleri seçme ve bulguları akademik bir çerçevede sunma becerilerini geliştirmeyi hedefler. Tez süreci, özgün düşünceyi ve araştırma etiğine uygun çalışmayı destekler.", en: "The program aims to develop specialists capable of conducting independent research in computer engineering. It strengthens critical literature review, research question formulation, method selection and academic presentation of findings. The thesis process supports original thinking and ethical research practice." },
  MAK: { tr: "Programın amacı; mekanik sistemlerin tasarım, üretim ve işletim süreçlerinde bilimsel ve teknik bilgiyi kullanabilen mühendisler yetiştirmektir. Mekanik, malzeme ve enerji bilgilerini birleştirerek güvenilir ve verimli çözümler geliştirmeyi; üretilebilirlik, maliyet ve çevresel etkiler arasında dengeli kararlar verebilme becerisini kazandırmayı hedefler.", en: "The program aims to develop engineers who can apply scientific and technical knowledge to the design, manufacture and operation of mechanical systems. It integrates mechanics, materials and energy to support reliable and efficient solutions, balancing manufacturability, cost and environmental impact." },
  IST: { tr: "Programın amacı; veriden anlamlı sonuçlar çıkarabilen ve belirsizlik altında karar verme süreçlerini destekleyebilen bireyler yetiştirmektir. Uygun veri toplama ve analiz yöntemlerini seçme, istatistiksel modeller kurma ve sonuçları sınırlılıklarıyla birlikte yorumlama becerilerini geliştirmeyi hedefler. Bulguların anlaşılır biçimde sunulması ve verilerin etik kullanımı bu yaklaşımın temel parçalarıdır.", en: "The program aims to develop the ability to draw meaningful conclusions from data and support decisions under uncertainty. It strengthens the selection of data collection and analysis methods, statistical modelling and interpretation of results with their limitations, alongside clear communication and ethical data use." },
  BPR: { tr: "Program, yazılım geliştirme ve bilgi sistemlerinin temel bileşenlerini uygulamalı biçimde öğretmeyi amaçlar. Öğrenciler programlama, web teknolojileri, veri tabanları ve teknik destek alanlarında mesleki beceriler geliştirir.", en: "The program teaches the practical foundations of software development and information systems. Students build vocational skills in programming, web technologies, databases and technical support." },
  HEM: { tr: "Program, birey ve toplum sağlığını koruma ve geliştirme süreçlerinde bilimsel bilgiye dayalı, güvenli ve etik hemşirelik bakımını planlayıp uygulayabilen mezunlar yetiştirmeyi amaçlar.", en: "The program prepares graduates to plan and provide safe, ethical nursing care based on evidence, supporting the health of individuals and communities." },
  ISL: { tr: "Program, işletmelerin temel işlevlerini analiz edebilen; yönetim, pazarlama, muhasebe ve insan kaynakları alanlarında veriye dayalı kararlar geliştirebilen mezunlar yetiştirmeyi amaçlar.", en: "The program develops graduates who can analyse core business functions and make evidence-informed decisions in management, marketing, accounting and human resources." },
  ORM: { tr: "Program, orman ekosistemlerini koruma ve doğal kaynakları sürdürülebilir biçimde yönetme konularında bilimsel ve teknik yöntemleri kullanabilen orman mühendisleri yetiştirmeyi amaçlar.", en: "The program prepares forest engineers to use scientific and technical methods to conserve forest ecosystems and manage natural resources sustainably." },
  DNB: { tr: "Program, deniz ve iç su ekosistemlerini anlayan; balıkçılık ve su ürünleri üretiminde çevresel, teknik ve toplumsal etkileri birlikte değerlendirebilen mühendisler yetiştirmeyi amaçlar.", en: "The program prepares engineers to understand marine and inland-water ecosystems and consider environmental, technical and social factors in fisheries and aquaculture." },
  "BIL-DR": { tr: "Program, bilgisayar mühendisliğinde bağımsız ve özgün araştırma yürütebilen, araştırma sonuçlarını bilimsel yöntemlerle değerlendiren ve alana katkı sunan araştırmacılar yetiştirmeyi amaçlar.", en: "The program develops researchers who can conduct independent, original work in computer engineering, evaluate results rigorously and contribute to the field." },
  INS: { tr: "Program; altyapı ve yapı sistemlerini güvenli, işlevsel ve sürdürülebilir biçimde tasarlayabilen mühendisler yetiştirmeyi amaçlar.", en: "The program prepares engineers to design safe, functional and sustainable structures and infrastructure systems." },
  KIM: { tr: "Program, kimyasal süreçleri kuramsal ve deneysel yöntemlerle inceleyebilen; laboratuvar verilerini güvenli ve etik biçimde değerlendiren mezunlar yetiştirmeyi amaçlar.", en: "The program develops graduates who investigate chemical processes through theory and experiment and evaluate laboratory data safely and ethically." },
  EKO: { tr: "Program, ekonomik davranışları ve politikaları analiz edebilen; nicel verileri karar süreçlerinde kullanabilen mezunlar yetiştirmeyi amaçlar.", en: "The program prepares graduates to analyse economic behaviour and policy and use quantitative evidence in decision-making." },
  DEN: { tr: "Program, denizel canlıları ve ekosistemleri bilimsel yöntemlerle inceleyebilen, biyolojik çeşitlilik ve koruma çalışmalarına katkı sunan mezunlar yetiştirmeyi amaçlar.", en: "The program develops graduates who study marine organisms and ecosystems scientifically and contribute to biodiversity and conservation." }
};
export default programAims;
